	var grid_data=[
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g5.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g5.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	}
	
	
	]

//------------------------------------------------

var goods_lists_main=[
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g5.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g1.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g5.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g4.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	},
	{	
		"src":"img/index/g3.jpg",
		"goods_name":"【年货节】【新品上市】A407UB-顽石14寸轻薄窄边框笔记本...",
		"price":"￥4999"											
	}
]

	var surport_main_list=[
	{
		"src":"img/index/g2.png",
		"name":"笔记本电脑"	
	},
	{
		"src":"img/surport/zhuji.png",
		"name":"台式电脑"	
	},
	{
		"src":"img/surport/xian.png",
		"name":"主板"	
	},
	{
		"src":"img/index/g2.png",
		"name":"显卡"	
	},
	{
		"src":"img/surport/zhuji.png",
		"name":"一体机"	
	},
	{
		"src":"img/surport/xian.png",
		"name":"笔记本电脑"	
	},
	]

	var generalProductList=[
	{
		"src":"img/surport/gamehand.png",
		"name":"家庭影音"
	},
	{
		"src":"img/surport/ear.png",
		"name":"耳机"
	},
	{
		"src":"img/surport/mouse.png",
		"name":"鼠标"
	},
	{
		"src":"img/surport/pad.png",
		"name":"平板"
	},
	{
		"src":"img/surport/ear.png",
		"name":"耳机"
	}
	]

	var aa=[
	{
		"name":"一体机"
	},
	{
		"name":"数位看板"
	},
	{
		"name":"笔记本电脑"
	},
	{
		"name":"台式电脑"
	},
	{
		"name":"液晶显示器"
	},
	{
		"name":"服务器/工作站"
	},
	{
		"name":"投影仪"
	},
	{
		"name":"网络产品"
	}
	]













